FROM node:16-alpine

RUN apk add --no-cache bash postgresql-client

RUN npm install -g sequelize-cli

WORKDIR /app

COPY package*.json .

RUN npm install 

COPY . .

EXPOSE 5000

CMD ["npm","run","dev"]