services:
  frontend:
    build: frontend
    ports: 
      - 3000:80
    environment:
      NODE_ENV: production
    depends_on:
      - backend
  backend:
    build:
      context: .
    ports: 
      - 5000:5000
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/moviesApp
      PORT: 5000
      JWT_SECRET: alskdfjlkasdfjlksa23123asdlfk
    depends_on:
      - mongo    
  mongo:
    image: mongo:4.2.0
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
volumes:
  mongo_data: