services:
  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    environment:
      - REACT_APP_LOCALHOST_KEY=chat-app-current-user
      - BACKEND_HOST=http://localhost:5000 
    depends_on:
      - backend
  backend:
    build: ./server
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://db:27017/chat
    depends_on:
      - db
  db:
    image: mongo:7.0
    expose:
      - 27017
    ports:
      - 27017:27017    
    volumes:
      - dbdata:/data/db
volumes:
  dbdata: