services:
  frontend:
    build:
      context: ./public
      args:
        - NODE_ENV=production
        - REACT_APP_LOCALHOST_KEY=chat-app-current-user
        - BACKEND_HOST=http://localhost:5000 
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: ./server
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      - C_NAME=one
      - PORT=5000
      - MONGO_URL=mongodb://db:27017/chat
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: mongo:7.0
    expose:
      - 27017
    ports:
      - 27017:27017    
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
  
  
# backend2:
#     build: ./server
#     expose:
#       - 5000
#     ports:
#       - 5002:5000
#     environment:
#       - C_NAME=two
#       - PORT=5000
#       - MONGO_URL=mongodb://db:27017/chat
#       - NODE_ENV=production
#     depends_on:
#       - db