services:
  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./public:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - REACT_APP_LOCALHOST_KEY=chat-app-current-user
      - BACKEND_HOST=http://localhost:5000 
  backend:
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URL=mongodb://db:27017/chat
    depends_on:
      - db
  db:
    image: mongo:7.0
    expose:
      - 27017
    ports:
      - 27017:27017    
    volumes:
      - dbdata:/data/db
volumes:
  dbdata: