services:
  frontend:
    build:
      context: ./client
    ports:
      - 3000:3000
    networks:
      - front-back
    volumes:
      - ./client:/app/frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    expose:
      - 3000
    networks:
      - front-back
      - back-db
    volumes:
      - ./server:/app/backend
    depends_on:
      - db

  db:
    image: mongo:5.0
    expose:
      - 27017
    networks:
      - back-db
    volumes:
      - dbdata:/data/db

networks:
  front-back:
  back-db:

volumes:
  dbdata: