services:
  frontend:
    build: ./mern/frontend
    ports:
      - 3000:3000 
    environment:
      REACT_APP_API_URL: http://backend:5000 
  backend:
    build: ./mern/backend
    ports:
      - 5000:5000
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase  
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0  
    ports:
      - 27017:27017 
    volumes:
      - mongo-data:/data/db  
volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally

