services:
  web1:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development
  web2:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3002:3000
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development
      
  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - web1
      - web2    