services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - PORT=5000
      - DB_URI=mongodb://db:27017/ecommerce
      - JWT_SECRET=supersecret
      - JWT_EXPIRE=1d
      - COOKIE_EXPIRE=5

    ports:
      - 5000:5000
    depends_on:
      - db
  
  db:
    image: mongo:7.0
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
volumes:
  mongo_data: