services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports: 
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - 5000:5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      MONGO_URI: mongodb://mongo:27017/moviesApp
      PORT: 5000
#      JWT_SECRET: alskdfjlkasdfjlksa23123asdlfk
    depends_on:
      - mongo    
  mongo:
    image: mongo:7.0
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
volumes:
  mongo_data: