services:
  frontend:
    build: 
      context: ./client
      args:
        - REACT_APP_API=http://localhost:80/graphql
        - NODE_ENV=production
        - REACT_APP_WS=ws://localhost:80/graphql    
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - nginx
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend1
      - backend2        
  backend1:
    hostname: backend-1
    build: ./server
    environment:
      NODE_ENV: production
      DB_PORT: 5432
      PORT: 5000
      PUBLIC_URL: http://localhost:3000
      JWT_SECRET: JWTSECRET
      DATABASE_URL: postgresql://postgres:9592@db:5432/les_chat

    ports:
      - 5001:5000
    depends_on:
      - db
  backend2:
    hostname: backend-2
    build: ./server
    environment:
      NODE_ENV: production
      DB_PORT: 5432
      PORT: 5000
      PUBLIC_URL: http://localhost:3000
      JWT_SECRET: JWTSECRET
      DATABASE_URL: postgresql://postgres:9592@db:5432/les_chat

    ports:
      - 5002:5000
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9592
      POSTGRES_DB: les_chat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data: