services:
  web1:
    build:
      context: .
      args:
        - REACT_APP_CONTAINER_NAME=web1   
    environment:
      - NODE_ENV=production
    ports: 
      - 3001:3000
  web2:
    build:
      context: .
      args:
        - REACT_APP_CONTAINER_NAME=web2
    environment:
      - NODE_ENV=production
    ports: 
      - 3002:3000
  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - web1
      - web2          