name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  
jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dep
        run: npm install
      - name: run tests
        run: npm run test

 