services:
  frontend:
    build:
      context: ./client
      args:
        - CLIENT_ROOT_URL=http://localhost:3000
        - API_URL=http://localhost:5000/api
        - NODE_ENV=production
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: ./server
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_URI: mongodb://db:27017/mern-starter
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mongo:7.0
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
volumes:
  mongo_data: