services:
  frontend1:
    build: .
    container_name: frontend1
    environment:
      - NODE_ENV=production
    expose: 
      - 80
  frontend2:
    build: .
    container_name: frontend2
    environment:
      - NODE_ENV=production
    expose: 
      - 80
  load-balancer:
    image: nginx:alpine
    container_name: load-balancer      
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2          