services:
  web1:
    build: .
    environment:
      - NODE_ENV=production
      - REACT_APP_CONTAINER_NAME=web1
    ports: 
      - 3001:3000
  web2:
    build: .
    environment:
      - NODE_ENV=production
      - REACT_APP_CONTAINER_NAME=web2
    ports: 
      - 3002:3000
  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - web1
      - web2          