services:
  frontend:
    build: ./frontend
    environment:
      NODE_ENV: production
      API: http://localhost:5000
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: ./backend
    environment:
      NODE_ENV: production
      DB_USER: my_user
      DB_PASSWORD: root
      DB_NAME: my_database
      DB_HOST: db
      DB_PORT: 5432
      PUBLIC_URL: http://localhost:3000
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data: