FROM python:2.7-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

RUN adduser -D flaskuser

USER flaskuser

EXPOSE 3000

CMD ["python","/api/index.py"]