services:
  frontend:
    build: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    build: ./backend
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_URI: mongodb://db:27017/ecommerce
      JWT_SECRET: supersecret
      JWT_EXPIRE: 1d
      COOKIE_EXPIRE: 5
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mongo:7.0
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
volumes:
  mongo_data: