FROM python:3.10-slim

WORKDIR /app

COPY requirement.txt . 

RUN pip install --upgrade pip && pip install -r requirement.txt

COPY . .

RUN adduser --disabled-password django_user 

USER django_user

EXPOSE 8000

CMD ["python","manage.py","runserver","0.0.0.0:8000"]