services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DJANGO_ENV=development
      - SECRET_KEY=${SECRET_KEY}
      - SECRET_ADMIN_URL=${SECRET_ADMIN_URL}
      - HCAPTCHA_SITEKEY=${HCAPTCHA_SITEKEY}
      - HCAPTCHA_SECRET=${HCAPTCHA_SECRET}
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    command: python manage.py runserver 0.0.0.0:8000
