FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt . 

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/* \  
    && pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY . .

RUN adduser --disabled-password django_user 

USER django_user

EXPOSE 8000

ENTRYPOINT ["/bin/bash","/app/entrypoint.sh"]