services:
  web:
    build: 
      args:
        DJANGO_ENV: production
        SECRET_KEY: your-very-secret-key
        SECRET_ADMIN_URL: admin/secret/
        HCAPTCHA_SITEKEY: your-hcaptcha-sitekey
        HCAPTCHA_SECRET: your-hcaptcha-secret
      context: .
    ports:
      - 8000:8000
    environment:
      - DJANGO_ENV=production
      - SECRET_KEY=your-very-secret-key
      - SECRET_ADMIN_URL=admin/secret/
      - HCAPTCHA_SITEKEY=your-hcaptcha-sitekey
      - HCAPTCHA_SECRET=your-hcaptcha-secret 
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    command: daphne -b 0.0.0.0 -p 8000 PrivatePing.asgi:application 
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:  