FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt .

# Install all system dependencies required for Pillow, psycopg2, cffi
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    libpq-dev \
    postgresql-client \
    libjpeg-dev \
    zlib1g-dev \
    libffi-dev \
    && pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && apt-get purge -y --auto-remove build-essential gcc \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN adduser --disabled-password django_user

USER django_user

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
