services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=-05sgp9!deq=q1nltm@^^2cc+v29i(tyybv3v2t77qi66czazj
      - STRIPE_SECRET_KEY=none
      - STRIPE_PUBLIC_KEY=none
     ports:
      - 8000:8000
    volumes:
      - ./:/app