services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      REACT_APP_API : http://localhost:5000/graphql
      REACT_APP_WS : ws://localhost:5000/graphql
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build:
      context:  ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      DB_PORT: 5432
      PUBLIC_URL: http://localhost:3000
      PORT: 5000
      JWT_SECRET: JWTSECRET
      
    ports:
      - 5000:5000
    depends_on:
      - db
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9592
      POSTGRES_DB: les_chat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data: