services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 5000:5000
    environment:
      NODE_ENV: development 
      POSTGRES_LOCAL_URL: postgres://postgres:@db:5432/postgres
      PORT: 5000
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgres/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
volumes:
  db_data: