FROM node:20-alpine

WORKDIR /app

# Install native build tools for bcrypt
RUN apk add --no-cache make g++ python3

COPY package*.json pnpm-lock.yaml ./

RUN npm install -g pnpm && pnpm install 

COPY . .

EXPOSE 3000 5000

CMD ["pnpm", "dev:all"]