services:
  web:
    build: 
      context: ./ 
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 5000:5000
    environment:
      NODE_ENV: production 
      POSTGRES_LOCAL_URL: postgres://postgres:password@db:5432/postgres
      PORT: 5000
      CHOKIDAR_USEPOLLING: true
      VITE_API_URL: http://localhost:5000/api
      ACCESS_TOKEN_SECRET: your_access_token_secret_here
      REFRESH_TOKEN_SECRET: your_refresh_token_secret_here
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgres/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

volumes:
  db_data:
